name: giant
dependencies:
- python=3
- cython
- numpy>=2.0.1
- matplotlib>=3.8.4
- pandas>=2.2.2
- spiceypy>=6.0.0
- astropy
- astroquery
- c-compiler
- conda-build
- dill
- lxml
- opencv
- psutil
- pyqt
- scipy
- setuptools
- sphinx
- pytables
