

from giant.image_processing.denoising.denoising import DENOISING_TYPE
from giant.image_processing.denoising.gaussian import GaussianDenoising, GaussianDenoisingOptions
from giant.image_processing.denoising.nonlocal_means_denoising import NlMeansDenoising, NlMeansDenoisingOptions
from giant.image_processing.denoising.tvl1 import TVL1Denoising, TVL1DenoisingOptions